import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from '../models/User.js';
import Restaurant from '../models/Restaurant.js';
import MenuItem from '../models/MenuItem.js';
import connectDB from '../config/database.js';

dotenv.config();

const seedData = async () => {
  try {
    await connectDB();

    console.log('Clearing existing data...');
    await User.deleteMany({ email: { $regex: '@seed.com$' } });
    await Restaurant.deleteMany({});
    await MenuItem.deleteMany({});

    console.log('Creating restaurant owners...');
    const owners = await User.create([
      { name: 'Raj Kumar', email: 'raj1@seed.com', password: 'password123', phone: '9876543210', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Priya Sharma', email: 'priya1@seed.com', password: 'password123', phone: '9876543211', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Amit Patel', email: 'amit1@seed.com', password: 'password123', phone: '9876543212', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Sneha Reddy', email: 'sneha1@seed.com', password: 'password123', phone: '9876543213', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Vikram Singh', email: 'vikram1@seed.com', password: 'password123', phone: '9876543214', role: 'restaurant_owner', authProvider: 'local' },
      
      { name: 'Deepak Nair', email: 'deepak@seed.com', password: 'password123', phone: '9876543215', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Anjali Gupta', email: 'anjali@seed.com', password: 'password123', phone: '9876543216', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Karthik Iyer', email: 'karthik@seed.com', password: 'password123', phone: '9876543217', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Pooja Verma', email: 'pooja@seed.com', password: 'password123', phone: '9876543218', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Arjun Kumar', email: 'arjun@seed.com', password: 'password123', phone: '9876543219', role: 'restaurant_owner', authProvider: 'local' },
      
      { name: 'Rohan Shah', email: 'rohan@seed.com', password: 'password123', phone: '9876543220', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Neha Kapoor', email: 'neha@seed.com', password: 'password123', phone: '9876543221', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Sanjay Desai', email: 'sanjay@seed.com', password: 'password123', phone: '9876543222', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Isha Joshi', email: 'isha@seed.com', password: 'password123', phone: '9876543223', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Manish Malhotra', email: 'manish@seed.com', password: 'password123', phone: '9876543224', role: 'restaurant_owner', authProvider: 'local' },
      
      { name: 'Rajesh Chopra', email: 'rajesh@seed.com', password: 'password123', phone: '9876543225', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Priya Bhat', email: 'priyabhat@seed.com', password: 'password123', phone: '9876543226', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Vikrant Sinha', email: 'vikrant@seed.com', password: 'password123', phone: '9876543227', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Divya Singh', email: 'divya@seed.com', password: 'password123', phone: '9876543228', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Nitin Sharma', email: 'nitin@seed.com', password: 'password123', phone: '9876543229', role: 'restaurant_owner', authProvider: 'local' },
      
      { name: 'Suresh Reddy', email: 'suresh@seed.com', password: 'password123', phone: '9876543230', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Anjum Khan', email: 'anjum@seed.com', password: 'password123', phone: '9876543231', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Lakshmi Naidu', email: 'lakshmi@seed.com', password: 'password123', phone: '9876543232', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Ashok Rao', email: 'ashok@seed.com', password: 'password123', phone: '9876543233', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Madhavi Singh', email: 'madhavi@seed.com', password: 'password123', phone: '9876543234', role: 'restaurant_owner', authProvider: 'local' },
      
      { name: 'Vishal Kulkarni', email: 'vishal@seed.com', password: 'password123', phone: '9876543235', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Shruti Pawar', email: 'shruti@seed.com', password: 'password123', phone: '9876543236', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Aarav Singh', email: 'aarav@seed.com', password: 'password123', phone: '9876543237', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Ritika Deshmukh', email: 'ritika@seed.com', password: 'password123', phone: '9876543238', role: 'restaurant_owner', authProvider: 'local' },
      { name: 'Harsh Bhatt', email: 'harsh@seed.com', password: 'password123', phone: '9876543239', role: 'restaurant_owner', authProvider: 'local' }
    ]);

    console.log('Creating restaurants...');
    const restaurants = await Restaurant.create([
      { owner: owners[0]._id, name: 'Biryani Palace', description: 'Authentic Hyderabadi Biryani and traditional Mughlai cuisine', cuisineType: ['Biryani', 'Mughlai'], location: { street: 'MG Road', city: 'Anantapur', state: 'Andhra Pradesh', pincode: '515001', landmark: 'Near Railway Station' }, contact: { phone: '9876543210', email: 'contact@biryanipalace.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '23:00', isOpen: true }, saturday: { open: '11:00', close: '23:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.5, totalReviews: 320, deliveryTime: '35-45 mins', minimumOrder: 200, deliveryFee: 30, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Fast Delivery'], popularDishes: ['Hyderabadi Biryani', 'Haleem', 'Kebab'], isActive: true, isVerified: true },
      { owner: owners[1]._id, name: 'South Indian Cafe', description: 'South Indian dosas, idlis and traditional south cuisine', cuisineType: ['South Indian'], location: { street: 'Lalbagh Street', city: 'Anantapur', state: 'Andhra Pradesh', pincode: '515002', landmark: 'City Center' }, contact: { phone: '9876543211', email: 'contact@southindian.com' }, operatingHours: { monday: { open: '07:00', close: '22:00', isOpen: true }, tuesday: { open: '07:00', close: '22:00', isOpen: true }, wednesday: { open: '07:00', close: '22:00', isOpen: true }, thursday: { open: '07:00', close: '22:00', isOpen: true }, friday: { open: '07:00', close: '22:00', isOpen: true }, saturday: { open: '07:00', close: '22:00', isOpen: true }, sunday: { open: '07:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.3, totalReviews: 245, deliveryTime: '25-35 mins', minimumOrder: 150, deliveryFee: 20, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Masala Dosa', 'Idli Sambar', 'Uttapam'], isActive: true, isVerified: true },
      { owner: owners[2]._id, name: 'Chinese Corner', description: 'Indo-Chinese fusion and authentic Chinese cuisine', cuisineType: ['Chinese'], location: { street: 'Ratan Bazar', city: 'Anantapur', state: 'Andhra Pradesh', pincode: '515003', landmark: 'Bus Stand' }, contact: { phone: '9876543212', email: 'contact@chinesecorner.com' }, operatingHours: { monday: { open: '12:00', close: '23:30', isOpen: true }, tuesday: { open: '12:00', close: '23:30', isOpen: true }, wednesday: { open: '12:00', close: '23:30', isOpen: true }, thursday: { open: '12:00', close: '23:30', isOpen: true }, friday: { open: '12:00', close: '23:30', isOpen: true }, saturday: { open: '12:00', close: '23:30', isOpen: true }, sunday: { open: '12:00', close: '23:30', isOpen: true } }, priceRange: '₹₹', averageRating: 4.1, totalReviews: 189, deliveryTime: '30-40 mins', minimumOrder: 180, deliveryFee: 25, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking'], popularDishes: ['Hakka Noodles', 'Manchurian', 'Fried Rice'], isActive: true, isVerified: true },
      { owner: owners[3]._id, name: 'Tandoor Kitchen', description: 'North Indian tandoori and traditional cuisine', cuisineType: ['North Indian', 'Tandoor'], location: { street: 'Dhone Road', city: 'Anantapur', state: 'Andhra Pradesh', pincode: '515004', landmark: 'Hospital Area' }, contact: { phone: '9876543213', email: 'contact@tandoori.com' }, operatingHours: { monday: { open: '08:00', close: '22:00', isOpen: true }, tuesday: { open: '08:00', close: '22:00', isOpen: true }, wednesday: { open: '08:00', close: '22:00', isOpen: true }, thursday: { open: '08:00', close: '22:00', isOpen: true }, friday: { open: '08:00', close: '22:00', isOpen: true }, saturday: { open: '08:00', close: '22:00', isOpen: true }, sunday: { open: '08:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.4, totalReviews: 210, deliveryTime: '30-40 mins', minimumOrder: 150, deliveryFee: 25, isPureVeg: false, features: ['Free Delivery', 'Home Delivery', 'Fast Delivery'], popularDishes: ['Tandoori Chicken', 'Paneer Tikka', 'Naan'], isActive: true, isVerified: true },
      { owner: owners[4]._id, name: 'Pizza Hub', description: 'Pizza, burgers and fast food', cuisineType: ['Pizza', 'Burger'], location: { street: 'Guntupalli Road', city: 'Anantapur', state: 'Andhra Pradesh', pincode: '515005', landmark: 'Market Area' }, contact: { phone: '9876543214', email: 'contact@pizzahub.com' }, operatingHours: { monday: { open: '10:00', close: '23:00', isOpen: true }, tuesday: { open: '10:00', close: '23:00', isOpen: true }, wednesday: { open: '10:00', close: '23:00', isOpen: true }, thursday: { open: '10:00', close: '23:00', isOpen: true }, friday: { open: '10:00', close: '00:00', isOpen: true }, saturday: { open: '10:00', close: '00:00', isOpen: true }, sunday: { open: '10:00', close: '23:00', isOpen: true } }, priceRange: '₹', averageRating: 4.2, totalReviews: 156, deliveryTime: '20-30 mins', minimumOrder: 100, deliveryFee: 15, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking', 'Takeaway'], popularDishes: ['Margherita Pizza', 'Cheese Burger', 'French Fries'], isActive: true, isVerified: true },

      { owner: owners[5]._id, name: 'Spice Kitchen', description: 'Modern North and South Indian cuisine', cuisineType: ['North Indian', 'South Indian'], location: { street: 'MG Road', city: 'Bangalore', state: 'Karnataka', pincode: '560001', landmark: 'Brigade Mall' }, contact: { phone: '9876543215', email: 'contact@spicekitchen.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.6, totalReviews: 450, deliveryTime: '30-40 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Table Booking'], popularDishes: ['Paneer Tikka', 'Butter Chicken', 'Biryani'], isActive: true, isVerified: true },
      { owner: owners[6]._id, name: 'Dosa Delight', description: 'Traditional South Indian specialty', cuisineType: ['South Indian'], location: { street: 'Indiranagar', city: 'Bangalore', state: 'Karnataka', pincode: '560038', landmark: 'City School' }, contact: { phone: '9876543216', email: 'contact@dosadelight.com' }, operatingHours: { monday: { open: '07:00', close: '22:00', isOpen: true }, tuesday: { open: '07:00', close: '22:00', isOpen: true }, wednesday: { open: '07:00', close: '22:00', isOpen: true }, thursday: { open: '07:00', close: '22:00', isOpen: true }, friday: { open: '07:00', close: '22:00', isOpen: true }, saturday: { open: '07:00', close: '22:00', isOpen: true }, sunday: { open: '07:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.5, totalReviews: 380, deliveryTime: '25-35 mins', minimumOrder: 120, deliveryFee: 20, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Masala Dosa', 'Idli Sambar', 'Uttapam'], isActive: true, isVerified: true },
      { owner: owners[7]._id, name: 'Pizza Paradise', description: 'Wood-fired pizzas and Italian cuisine', cuisineType: ['Pizza', 'Italian'], location: { street: 'Koramangala', city: 'Bangalore', state: 'Karnataka', pincode: '560034', landmark: 'Sony Signal' }, contact: { phone: '9876543217', email: 'contact@pizzaparadise.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.7, totalReviews: 520, deliveryTime: '40-50 mins', minimumOrder: 300, deliveryFee: 40, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Margherita Pizza', 'Pepperoni Pizza', 'Pasta Carbonara'], isActive: true, isVerified: true },
      { owner: owners[8]._id, name: 'Healthy Bites', description: 'Nutritious salads and healthy meals', cuisineType: ['Healthy', 'Salads'], location: { street: 'Whitefield', city: 'Bangalore', state: 'Karnataka', pincode: '560066', landmark: 'Tech Park' }, contact: { phone: '9876543218', email: 'contact@healthybites.com' }, operatingHours: { monday: { open: '08:00', close: '21:00', isOpen: true }, tuesday: { open: '08:00', close: '21:00', isOpen: true }, wednesday: { open: '08:00', close: '21:00', isOpen: true }, thursday: { open: '08:00', close: '21:00', isOpen: true }, friday: { open: '08:00', close: '21:00', isOpen: true }, saturday: { open: '08:00', close: '21:00', isOpen: true }, sunday: { open: '08:00', close: '21:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.4, totalReviews: 290, deliveryTime: '25-35 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Greek Salad', 'Protein Bowl', 'Green Smoothie'], isActive: true, isVerified: true },
      { owner: owners[9]._id, name: 'Chinese Dragon', description: 'Chinese fusion and Asian cuisine', cuisineType: ['Chinese'], location: { street: 'JP Nagar', city: 'Bangalore', state: 'Karnataka', pincode: '560078', landmark: 'Metro Station' }, contact: { phone: '9876543219', email: 'contact@chinesedragon.com' }, operatingHours: { monday: { open: '12:00', close: '23:30', isOpen: true }, tuesday: { open: '12:00', close: '23:30', isOpen: true }, wednesday: { open: '12:00', close: '23:30', isOpen: true }, thursday: { open: '12:00', close: '23:30', isOpen: true }, friday: { open: '12:00', close: '00:00', isOpen: true }, saturday: { open: '12:00', close: '00:00', isOpen: true }, sunday: { open: '12:00', close: '23:30', isOpen: true } }, priceRange: '₹₹', averageRating: 4.3, totalReviews: 350, deliveryTime: '30-40 mins', minimumOrder: 180, deliveryFee: 25, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking', 'Takeaway'], popularDishes: ['Hakka Noodles', 'Manchurian', 'Fried Rice'], isActive: true, isVerified: true },

      { owner: owners[10]._id, name: 'Street Food Express', description: 'Famous Mumbai street food', cuisineType: ['Street Food', 'Snacks'], location: { street: 'Lower Parel', city: 'Mumbai', state: 'Maharashtra', pincode: '400013', landmark: 'Railway Station' }, contact: { phone: '9876543220', email: 'contact@streetfood.com' }, operatingHours: { monday: { open: '09:00', close: '23:00', isOpen: true }, tuesday: { open: '09:00', close: '23:00', isOpen: true }, wednesday: { open: '09:00', close: '23:00', isOpen: true }, thursday: { open: '09:00', close: '23:00', isOpen: true }, friday: { open: '09:00', close: '00:00', isOpen: true }, saturday: { open: '09:00', close: '00:00', isOpen: true }, sunday: { open: '09:00', close: '23:00', isOpen: true } }, priceRange: '₹', averageRating: 4.4, totalReviews: 580, deliveryTime: '20-30 mins', minimumOrder: 80, deliveryFee: 15, isPureVeg: true, features: ['Fast Delivery', 'Takeaway', 'Home Delivery'], popularDishes: ['Vada Pav', 'Misal Pav', 'Pav Bhaji'], isActive: true, isVerified: true },
      { owner: owners[11]._id, name: 'Seafood Delight', description: 'Fresh seafood and coastal cuisine', cuisineType: ['Seafood', 'Continental'], location: { street: 'Marine Drive', city: 'Mumbai', state: 'Maharashtra', pincode: '400020', landmark: 'Worli Sea Link' }, contact: { phone: '9876543221', email: 'contact@seafood.com' }, operatingHours: { monday: { open: '12:00', close: '00:00', isOpen: true }, tuesday: { open: '12:00', close: '00:00', isOpen: true }, wednesday: { open: '12:00', close: '00:00', isOpen: true }, thursday: { open: '12:00', close: '00:00', isOpen: true }, friday: { open: '12:00', close: '01:00', isOpen: true }, saturday: { open: '12:00', close: '01:00', isOpen: true }, sunday: { open: '12:00', close: '00:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.7, totalReviews: 610, deliveryTime: '40-50 mins', minimumOrder: 400, deliveryFee: 50, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Table Booking'], popularDishes: ['Fish Curry', 'Prawns Butter Garlic', 'Crab Masala'], isActive: true, isVerified: true },
      { owner: owners[12]._id, name: 'Biryani Bazaar', description: 'Authentic biryani and Mughlai cuisine', cuisineType: ['Biryani', 'Mughlai'], location: { street: 'Bandra', city: 'Mumbai', state: 'Maharashtra', pincode: '400050', landmark: 'Linking Road' }, contact: { phone: '9876543222', email: 'contact@biryani.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.5, totalReviews: 420, deliveryTime: '35-45 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Hyderabadi Biryani', 'Haleem', 'Kebab'], isActive: true, isVerified: true },
      { owner: owners[13]._id, name: 'Italian Kitchen', description: 'Authentic Italian and pasta cuisine', cuisineType: ['Italian'], location: { street: 'Powai', city: 'Mumbai', state: 'Maharashtra', pincode: '400076', landmark: 'Phoenix Mall' }, contact: { phone: '9876543223', email: 'contact@italian.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.6, totalReviews: 390, deliveryTime: '35-45 mins', minimumOrder: 300, deliveryFee: 40, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Spaghetti Carbonara', 'Penne Arrabbiata', 'Risotto'], isActive: true, isVerified: true },
      { owner: owners[14]._id, name: 'Burger Station', description: 'Gourmet burgers and fast food', cuisineType: ['Burger', 'Fast Food'], location: { street: 'Thane', city: 'Mumbai', state: 'Maharashtra', pincode: '400615', landmark: 'Viviana Mall' }, contact: { phone: '9876543224', email: 'contact@burger.com' }, operatingHours: { monday: { open: '10:00', close: '23:00', isOpen: true }, tuesday: { open: '10:00', close: '23:00', isOpen: true }, wednesday: { open: '10:00', close: '23:00', isOpen: true }, thursday: { open: '10:00', close: '23:00', isOpen: true }, friday: { open: '10:00', close: '00:00', isOpen: true }, saturday: { open: '10:00', close: '00:00', isOpen: true }, sunday: { open: '10:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.3, totalReviews: 310, deliveryTime: '25-35 mins', minimumOrder: 150, deliveryFee: 25, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking', 'Takeaway'], popularDishes: ['Cheese Burger', 'Double Decker', 'Crispy Fries'], isActive: true, isVerified: true },

      { owner: owners[15]._id, name: 'Chaat Paradise', description: 'Traditional Delhi street food and chaat', cuisineType: ['Street Food', 'Snacks'], location: { street: 'Chandni Chowk', city: 'Delhi', state: 'Delhi', pincode: '110006', landmark: 'Red Fort' }, contact: { phone: '9876543225', email: 'contact@chaat.com' }, operatingHours: { monday: { open: '10:00', close: '23:00', isOpen: true }, tuesday: { open: '10:00', close: '23:00', isOpen: true }, wednesday: { open: '10:00', close: '23:00', isOpen: true }, thursday: { open: '10:00', close: '23:00', isOpen: true }, friday: { open: '10:00', close: '00:00', isOpen: true }, saturday: { open: '10:00', close: '00:00', isOpen: true }, sunday: { open: '10:00', close: '23:00', isOpen: true } }, priceRange: '₹', averageRating: 4.4, totalReviews: 520, deliveryTime: '20-30 mins', minimumOrder: 100, deliveryFee: 20, isPureVeg: true, features: ['Fast Delivery', 'Takeaway', 'Home Delivery'], popularDishes: ['Gol Gappa', 'Aloo Tikki', 'Chole Bhature'], isActive: true, isVerified: true },
      { owner: owners[16]._id, name: 'Tandoori House', description: 'North Indian tandoori and Mughlai specialties', cuisineType: ['North Indian', 'Tandoor', 'Mughlai'], location: { street: 'Connaught Place', city: 'Delhi', state: 'Delhi', pincode: '110001', landmark: 'Central Delhi' }, contact: { phone: '9876543226', email: 'contact@tandoor.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.6, totalReviews: 480, deliveryTime: '35-45 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Tandoori Chicken', 'Butter Chicken', 'Naan'], isActive: true, isVerified: true },
      { owner: owners[17]._id, name: 'South Indian Cafe', description: 'South Indian food in the heart of Delhi', cuisineType: ['South Indian'], location: { street: 'Karol Bagh', city: 'Delhi', state: 'Delhi', pincode: '110005', landmark: 'Metro Station' }, contact: { phone: '9876543227', email: 'contact@southcafe.com' }, operatingHours: { monday: { open: '07:00', close: '22:00', isOpen: true }, tuesday: { open: '07:00', close: '22:00', isOpen: true }, wednesday: { open: '07:00', close: '22:00', isOpen: true }, thursday: { open: '07:00', close: '22:00', isOpen: true }, friday: { open: '07:00', close: '22:00', isOpen: true }, saturday: { open: '07:00', close: '22:00', isOpen: true }, sunday: { open: '07:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.5, totalReviews: 350, deliveryTime: '25-35 mins', minimumOrder: 120, deliveryFee: 20, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Masala Dosa', 'Idli Sambar', 'Uttapam'], isActive: true, isVerified: true },
      { owner: owners[18]._id, name: 'Mughlai Paradise', description: 'Premium Mughlai cuisine with authentic recipes', cuisineType: ['Mughlai', 'Biryani'], location: { street: 'Dwarka', city: 'Delhi', state: 'Delhi', pincode: '110075', landmark: 'Sector 12' }, contact: { phone: '9876543228', email: 'contact@mughlai.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.5, totalReviews: 420, deliveryTime: '35-45 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Table Booking'], popularDishes: ['Shahi Tukda', 'Murgh Mussallam', 'Biryani'], isActive: true, isVerified: true },
      { owner: owners[19]._id, name: 'Continental Bites', description: 'Continental and Italian fusion cuisine', cuisineType: ['Continental', 'Italian'], location: { street: 'Greater Kailash', city: 'Delhi', state: 'Delhi', pincode: '110048', landmark: 'GK-1 Market' }, contact: { phone: '9876543229', email: 'contact@continental.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.4, totalReviews: 280, deliveryTime: '35-45 mins', minimumOrder: 300, deliveryFee: 40, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Grilled Fish', 'Pasta Primavera', 'Crispy Spring Rolls'], isActive: true, isVerified: true },

      { owner: owners[20]._id, name: 'Biryani House', description: 'World-famous Hyderabadi biryani and local delicacies', cuisineType: ['Biryani', 'Mughlai'], location: { street: 'Charminar', city: 'Hyderabad', state: 'Telangana', pincode: '500002', landmark: 'Historic Charminar' }, contact: { phone: '9876543230', email: 'contact@hydbir.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.7, totalReviews: 680, deliveryTime: '35-45 mins', minimumOrder: 200, deliveryFee: 30, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Hyderabadi Biryani', 'Haleem', 'Kebab'], isActive: true, isVerified: true },
      { owner: owners[21]._id, name: 'Kebab Corner', description: 'Authentic kebabs and grilled specialties', cuisineType: ['Tandoor', 'Mughlai'], location: { street: 'Secunderabad', city: 'Hyderabad', state: 'Telangana', pincode: '500003', landmark: 'Clock Tower' }, contact: { phone: '9876543231', email: 'contact@kebab.com' }, operatingHours: { monday: { open: '12:00', close: '23:00', isOpen: true }, tuesday: { open: '12:00', close: '23:00', isOpen: true }, wednesday: { open: '12:00', close: '23:00', isOpen: true }, thursday: { open: '12:00', close: '23:00', isOpen: true }, friday: { open: '12:00', close: '00:00', isOpen: true }, saturday: { open: '12:00', close: '00:00', isOpen: true }, sunday: { open: '12:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.6, totalReviews: 420, deliveryTime: '30-40 mins', minimumOrder: 200, deliveryFee: 30, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking', 'Takeaway'], popularDishes: ['Shami Kebab', 'Seekh Kebab', 'Kakori Kebab'], isActive: true, isVerified: true },
      { owner: owners[22]._id, name: 'Haleem House', description: 'Famous Hyderabadi haleem and meat specialties', cuisineType: ['Mughlai', 'Biryani'], location: { street: 'HITEC City', city: 'Hyderabad', state: 'Telangana', pincode: '500081', landmark: 'Near IKEA' }, contact: { phone: '9876543232', email: 'contact@haleem.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.5, totalReviews: 380, deliveryTime: '35-45 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Mutton Haleem', 'Chicken Haleem', 'Paya'], isActive: true, isVerified: true },
      { owner: owners[23]._id, name: 'Vegetarian Delight', description: 'Pure vegetarian South and North Indian cuisine', cuisineType: ['South Indian', 'North Indian'], location: { street: 'Banjara Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500034', landmark: 'Road No. 12' }, contact: { phone: '9876543233', email: 'contact@vegdel.com' }, operatingHours: { monday: { open: '07:30', close: '22:00', isOpen: true }, tuesday: { open: '07:30', close: '22:00', isOpen: true }, wednesday: { open: '07:30', close: '22:00', isOpen: true }, thursday: { open: '07:30', close: '22:00', isOpen: true }, friday: { open: '07:30', close: '22:00', isOpen: true }, saturday: { open: '07:30', close: '22:00', isOpen: true }, sunday: { open: '07:30', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.4, totalReviews: 320, deliveryTime: '25-35 mins', minimumOrder: 150, deliveryFee: 25, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Masala Dosa', 'Uttapam', 'Chole Bhature'], isActive: true, isVerified: true },
      { owner: owners[24]._id, name: 'Fusion Kitchen', description: 'Modern fusion of Hyderabadi and international cuisine', cuisineType: ['Biryani', 'Continental'], location: { street: 'Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', landmark: 'Inorbit Mall' }, contact: { phone: '9876543234', email: 'contact@fusion.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.5, totalReviews: 290, deliveryTime: '35-45 mins', minimumOrder: 300, deliveryFee: 40, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Table Booking'], popularDishes: ['Fusion Biryani', 'Tandoori Pasta', 'Continental Kebab'], isActive: true, isVerified: true },

      { owner: owners[25]._id, name: 'Misal Pav House', description: 'Traditional Pune misal pav and local cuisine', cuisineType: ['Street Food', 'Snacks'], location: { street: 'Shaniwar Wada', city: 'Pune', state: 'Maharashtra', pincode: '411002', landmark: 'Historic Area' }, contact: { phone: '9876543235', email: 'contact@misal.com' }, operatingHours: { monday: { open: '07:00', close: '22:00', isOpen: true }, tuesday: { open: '07:00', close: '22:00', isOpen: true }, wednesday: { open: '07:00', close: '22:00', isOpen: true }, thursday: { open: '07:00', close: '22:00', isOpen: true }, friday: { open: '07:00', close: '22:00', isOpen: true }, saturday: { open: '07:00', close: '22:00', isOpen: true }, sunday: { open: '07:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.6, totalReviews: 520, deliveryTime: '20-30 mins', minimumOrder: 100, deliveryFee: 20, isPureVeg: true, features: ['Fast Delivery', 'Takeaway', 'Home Delivery'], popularDishes: ['Misal Pav', 'Poha Jalebi', 'Upma'], isActive: true, isVerified: true },
      { owner: owners[26]._id, name: 'Tandoori Kitchen', description: 'North Indian tandoori specialties and biryani', cuisineType: ['North Indian', 'Tandoor', 'Biryani'], location: { street: 'Kalyani Nagar', city: 'Pune', state: 'Maharashtra', pincode: '411006', landmark: 'Markets' }, contact: { phone: '9876543236', email: 'contact@tandoori.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.5, totalReviews: 410, deliveryTime: '35-45 mins', minimumOrder: 250, deliveryFee: 35, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Tandoori Chicken', 'Butter Chicken', 'Biryani'], isActive: true, isVerified: true },
      { owner: owners[27]._id, name: 'Pizza Nest', description: 'Wood-fired pizzas and Italian delights', cuisineType: ['Pizza', 'Italian'], location: { street: 'Baner', city: 'Pune', state: 'Maharashtra', pincode: '411045', landmark: 'Phoenix Market City' }, contact: { phone: '9876543237', email: 'contact@pizza.com' }, operatingHours: { monday: { open: '11:00', close: '23:00', isOpen: true }, tuesday: { open: '11:00', close: '23:00', isOpen: true }, wednesday: { open: '11:00', close: '23:00', isOpen: true }, thursday: { open: '11:00', close: '23:00', isOpen: true }, friday: { open: '11:00', close: '00:00', isOpen: true }, saturday: { open: '11:00', close: '00:00', isOpen: true }, sunday: { open: '11:00', close: '23:00', isOpen: true } }, priceRange: '₹₹₹', averageRating: 4.6, totalReviews: 480, deliveryTime: '40-50 mins', minimumOrder: 300, deliveryFee: 40, isPureVeg: false, features: ['Free Delivery', 'Live Tracking', 'Home Delivery'], popularDishes: ['Margherita Pizza', 'Pepperoni Pizza', 'Pasta Carbonara'], isActive: true, isVerified: true },
      { owner: owners[28]._id, name: 'South Indian Cafe', description: 'South Indian breakfast and meals', cuisineType: ['South Indian'], location: { street: 'Viman Nagar', city: 'Pune', state: 'Maharashtra', pincode: '411014', landmark: 'Airport Road' }, contact: { phone: '9876543238', email: 'contact@southpune.com' }, operatingHours: { monday: { open: '07:00', close: '22:00', isOpen: true }, tuesday: { open: '07:00', close: '22:00', isOpen: true }, wednesday: { open: '07:00', close: '22:00', isOpen: true }, thursday: { open: '07:00', close: '22:00', isOpen: true }, friday: { open: '07:00', close: '22:00', isOpen: true }, saturday: { open: '07:00', close: '22:00', isOpen: true }, sunday: { open: '07:00', close: '22:00', isOpen: true } }, priceRange: '₹', averageRating: 4.4, totalReviews: 350, deliveryTime: '25-35 mins', minimumOrder: 120, deliveryFee: 20, isPureVeg: true, features: ['Pure Veg', 'Contactless Delivery', 'Fast Delivery'], popularDishes: ['Masala Dosa', 'Idli Sambar', 'Uttapam'], isActive: true, isVerified: true },
      { owner: owners[29]._id, name: 'Asian Express', description: 'Asian cuisine fusion with Chinese and Thai flavors', cuisineType: ['Chinese', 'Fast Food'], location: { street: 'Hinjewadi', city: 'Pune', state: 'Maharashtra', pincode: '411057', landmark: 'Tech Park' }, contact: { phone: '9876543239', email: 'contact@asian.com' }, operatingHours: { monday: { open: '12:00', close: '23:00', isOpen: true }, tuesday: { open: '12:00', close: '23:00', isOpen: true }, wednesday: { open: '12:00', close: '23:00', isOpen: true }, thursday: { open: '12:00', close: '23:00', isOpen: true }, friday: { open: '12:00', close: '00:00', isOpen: true }, saturday: { open: '12:00', close: '00:00', isOpen: true }, sunday: { open: '12:00', close: '23:00', isOpen: true } }, priceRange: '₹₹', averageRating: 4.3, totalReviews: 290, deliveryTime: '30-40 mins', minimumOrder: 200, deliveryFee: 30, isPureVeg: false, features: ['Fast Delivery', 'Live Tracking', 'Takeaway'], popularDishes: ['Thai Green Curry', 'Pad Thai', 'Chinese Noodles'], isActive: true, isVerified: true }
    ]);

    console.log('Creating menu items (10+ per restaurant)...');
    const createMenuItems = (restaurantId, items) => {
      return items.map(item => ({ ...item, restaurant: restaurantId }));
    };

    const biryaniMenuItems = [
      { name: 'Hyderabadi Chicken Biryani', description: 'Authentic Hyderabadi biryani with tender chicken', category: 'Rice & Biryani', price: 280, isVeg: false, spiceLevel: 'medium', nutritionalInfo: { calories: 650, protein: 35, carbs: 75, fat: 22 }, allergens: ['Dairy'], portionSize: '1 serving (500g)', preparationTime: 25, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (500g)', price: 0 }, { name: 'Large (750g)', price: 60 }, { name: 'Extra Large (1kg)', price: 120 }], isRequired: true, allowMultiple: false }, { name: 'Raita/Yogurt', options: [{ name: 'No Raita', price: 0 }, { name: 'With Raita', price: 0 }, { name: 'Extra Raita', price: 30 }], isRequired: false, allowMultiple: false }] },
      { name: 'Mutton Biryani', description: 'Tender mutton pieces with aromatic rice', category: 'Rice & Biryani', price: 320, isVeg: false, spiceLevel: 'medium', nutritionalInfo: { calories: 700, protein: 40, carbs: 75, fat: 25 }, allergens: ['None'], portionSize: '1 serving (500g)', preparationTime: 30, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (500g)', price: 0 }, { name: 'Large (750g)', price: 80 }, { name: 'Extra Large (1kg)', price: 150 }], isRequired: true, allowMultiple: false }, { name: 'Extras', options: [{ name: 'Shorba (Gravy)', price: 0 }, { name: 'Fried Onions', price: 20 }, { name: 'Boiled Eggs', price: 50 }], isRequired: false, allowMultiple: true }] },
      { name: 'Paneer Biryani', description: 'Vegetarian biryani with cottage cheese', category: 'Rice & Biryani', price: 240, isVeg: true, spiceLevel: 'medium', nutritionalInfo: { calories: 580, protein: 22, carbs: 68, fat: 25 }, allergens: ['Dairy', 'Nuts'], portionSize: '1 serving (500g)', preparationTime: 25, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (500g)', price: 0 }, { name: 'Large (750g)', price: 50 }, { name: 'Extra Large (1kg)', price: 100 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Extra Paneer', price: 40 }, { name: 'With Raita', price: 0 }], isRequired: false, allowMultiple: true }] },
      { name: 'Chicken Tikka', description: 'Spicy grilled chicken with yogurt marinade', category: 'Starters', price: 220, isVeg: false, spiceLevel: 'hot', nutritionalInfo: { calories: 280, protein: 32, carbs: 8, fat: 12 }, allergens: ['Dairy'], portionSize: '6 pieces', preparationTime: 15, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Quantity', options: [{ name: '6 Pieces', price: 0 }, { name: '12 Pieces', price: 220 }, { name: '18 Pieces', price: 440 }], isRequired: true, allowMultiple: false }, { name: 'Sauce', options: [{ name: 'Mint Chutney', price: 0 }, { name: 'Tamarind Chutney', price: 0 }, { name: 'Both Chutneys', price: 15 }], isRequired: false, allowMultiple: false }] },
      { name: 'Shami Kebab', description: 'Minced meat kebab with spices', category: 'Starters', price: 180, isVeg: false, spiceLevel: 'medium', nutritionalInfo: { calories: 320, protein: 25, carbs: 20, fat: 16 }, allergens: ['Eggs', 'Gluten'], portionSize: '4 pieces', preparationTime: 15, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '4 Pieces', price: 0 }, { name: '8 Pieces', price: 180 }, { name: '12 Pieces', price: 360 }], isRequired: true, allowMultiple: false }, { name: 'Sauce', options: [{ name: 'Mint Chutney', price: 0 }, { name: 'Tamarind Chutney', price: 0 }, { name: 'No Sauce', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Naan', description: 'Traditional Indian bread baked in tandoor', category: 'Breads', price: 40, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 250, protein: 7, carbs: 45, fat: 5 }, allergens: ['Gluten', 'Dairy'], portionSize: '1 piece', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Naan Variety', options: [{ name: 'Plain Naan', price: 0 }, { name: 'Butter Naan', price: 10 }, { name: 'Garlic Naan', price: 15 }, { name: 'Cheese Naan', price: 20 }, { name: 'Onion Naan', price: 15 }], isRequired: true, allowMultiple: false }, { name: 'Quantity', options: [{ name: '1 Piece', price: 0 }, { name: '2 Pieces', price: 40 }, { name: '4 Pieces', price: 80 }], isRequired: true, allowMultiple: false }] },
      { name: 'Raita', description: 'Yogurt with cucumber and spices', category: 'Other', price: 80, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 80, protein: 4, carbs: 8, fat: 3 }, allergens: ['Dairy'], portionSize: '1 bowl (150ml)', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Raita Type', options: [{ name: 'Cucumber Raita', price: 0 }, { name: 'Pineapple Raita', price: 10 }, { name: 'Mint Raita', price: 0 }, { name: 'Boondi Raita', price: 15 }], isRequired: true, allowMultiple: false }, { name: 'Size', options: [{ name: 'Regular (150ml)', price: 0 }, { name: 'Large (250ml)', price: 30 }], isRequired: true, allowMultiple: false }] },
      { name: 'Lachcha Paratha', description: 'Layered Indian flatbread with butter', category: 'Breads', price: 60, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 220, protein: 5, carbs: 40, fat: 6 }, allergens: ['Gluten', 'Dairy'], portionSize: '1 piece', preparationTime: 8, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Paratha Variety', options: [{ name: 'Plain Paratha', price: 0 }, { name: 'Aloo Paratha', price: 20 }, { name: 'Paneer Paratha', price: 30 }, { name: 'Mooli Paratha', price: 20 }], isRequired: true, allowMultiple: false }, { name: 'Quantity', options: [{ name: '1 Piece', price: 0 }, { name: '2 Pieces', price: 60 }], isRequired: true, allowMultiple: false }] },
      { name: 'Biryani Rice', description: 'Plain aromatic biryani rice', category: 'Rice & Biryani', price: 150, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 400, protein: 8, carbs: 85, fat: 3 }, allergens: ['None'], portionSize: '1 serving (300g)', preparationTime: 20, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Portion Size', options: [{ name: 'Regular (300g)', price: 0 }, { name: 'Large (500g)', price: 60 }, { name: 'Extra Large (750g)', price: 100 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Fried Onions', price: 15 }, { name: 'Boiled Eggs', price: 40 }], isRequired: false, allowMultiple: true }] },
      { name: 'Dal', description: 'Creamy lentil curry', category: 'Main Course', price: 120, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 200, protein: 12, carbs: 28, fat: 5 }, allergens: ['None'], portionSize: '1 serving (250g)', preparationTime: 15, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Size', options: [{ name: 'Regular (250g)', price: 0 }, { name: 'Large (400g)', price: 50 }], isRequired: true, allowMultiple: false }] },
    ];

    const southIndianMenuItems = [
      { name: 'Masala Dosa', description: 'Crispy rice crepe with spiced potato filling', category: 'South Indian', price: 80, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 320, protein: 8, carbs: 52, fat: 8 }, allergens: ['None'], portionSize: '1 dosa', preparationTime: 12, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Dosa Filling', options: [{ name: 'Masala Potato', price: 0 }, { name: 'Cheese & Potato', price: 15 }, { name: 'Paneer & Potato', price: 20 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Served With', options: [{ name: 'Sambar & Chutney', price: 0 }, { name: 'Chutney Only', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Cheese Dosa', description: 'Dosa with melted cheese and vegetables', category: 'South Indian', price: 100, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 380, protein: 10, carbs: 54, fat: 14 }, allergens: ['Dairy'], portionSize: '1 dosa', preparationTime: 12, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Cheese Type', options: [{ name: 'Regular Cheese', price: 0 }, { name: 'Extra Cheese', price: 15 }, { name: 'Mozzarella Cheese', price: 20 }], isRequired: true, allowMultiple: false }, { name: 'Vegetables', options: [{ name: 'Tomato', price: 0 }, { name: 'Onion', price: 0 }, { name: 'Both', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Paneer Dosa', description: 'Dosa with paneer and vegetables', category: 'South Indian', price: 110, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 390, protein: 12, carbs: 54, fat: 14 }, allergens: ['Dairy'], portionSize: '1 dosa', preparationTime: 14, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Paneer Style', options: [{ name: 'Fried Paneer', price: 0 }, { name: 'Marinated Paneer', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Extra Paneer', price: 30 }, { name: 'Cheese', price: 15 }], isRequired: false, allowMultiple: true }] },
      { name: 'Idli Sambar', description: 'Steamed rice cakes served with sambar and chutney', category: 'Breakfast', price: 60, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 240, protein: 6, carbs: 48, fat: 2 }, allergens: ['None'], portionSize: '4 idlis', preparationTime: 10, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Quantity', options: [{ name: '4 Idlis', price: 0 }, { name: '6 Idlis', price: 30 }, { name: '8 Idlis', price: 60 }], isRequired: true, allowMultiple: false }, { name: 'Sambar Type', options: [{ name: 'Regular Sambar', price: 0 }, { name: 'Spicy Sambar', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Chutney Selection', options: [{ name: 'Coconut Chutney', price: 0 }, { name: 'Mint Chutney', price: 0 }, { name: 'Both', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Uttapam', description: 'Savory rice pancake with vegetables', category: 'South Indian', price: 70, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 280, protein: 7, carbs: 45, fat: 6 }, allergens: ['None'], portionSize: '1 uttapam', preparationTime: 12, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Toppings', options: [{ name: 'Tomato & Onion', price: 0 }, { name: 'Corn & Pepper', price: 10 }, { name: 'Mixed Vegetables', price: 15 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Coffee', description: 'South Indian filter coffee', category: 'Beverages', price: 40, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 50, protein: 2, carbs: 8, fat: 1 }, allergens: ['Dairy'], portionSize: '1 cup (150ml)', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Coffee Type', options: [{ name: 'Regular Coffee', price: 0 }, { name: 'Black Coffee', price: 0 }, { name: 'Extra Strong', price: 5 }], isRequired: true, allowMultiple: false }, { name: 'Milk', options: [{ name: 'Full Milk', price: 0 }, { name: 'Half Milk', price: 0 }, { name: 'No Milk', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Sugar', options: [{ name: 'Normal Sugar', price: 0 }, { name: 'Less Sugar', price: 0 }, { name: 'No Sugar', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Kesari', description: 'Sweet semolina pudding', category: 'Desserts', price: 50, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 180, protein: 3, carbs: 35, fat: 5 }, allergens: ['Dairy', 'Nuts'], portionSize: '1 serving (100g)', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Size', options: [{ name: 'Regular (100g)', price: 0 }, { name: 'Large (150g)', price: 25 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Cashew Nuts', price: 10 }, { name: 'Raisins', price: 5 }, { name: 'Both', price: 15 }], isRequired: false, allowMultiple: false }] },
      { name: 'Medu Vada', description: 'Fried lentil donuts', category: 'Snacks', price: 45, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 200, protein: 5, carbs: 25, fat: 8 }, allergens: ['None'], portionSize: '2 vadas', preparationTime: 10, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '2 Vadas', price: 0 }, { name: '4 Vadas', price: 45 }, { name: '6 Vadas', price: 90 }], isRequired: true, allowMultiple: false }, { name: 'Served With', options: [{ name: 'Sambar Only', price: 0 }, { name: 'Chutney Only', price: 0 }, { name: 'Both', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Appam', description: 'Fermented rice pancake', category: 'South Indian', price: 55, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 250, protein: 5, carbs: 45, fat: 4 }, allergens: ['None'], portionSize: '2 appams', preparationTime: 10, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '2 Appams', price: 0 }, { name: '4 Appams', price: 55 }], isRequired: true, allowMultiple: false }, { name: 'Curry Pairing', options: [{ name: 'Stew', price: 0 }, { name: 'Vegetable Curry', price: 0 }, { name: 'None', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Sambar', description: 'Vegetable curry with lentils and spices', category: 'Main Course', price: 50, isVeg: true, spiceLevel: 'medium', nutritionalInfo: { calories: 120, protein: 4, carbs: 15, fat: 5 }, allergens: ['None'], portionSize: '1 serving (200ml)', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Size', options: [{ name: 'Regular (200ml)', price: 0 }, { name: 'Large (350ml)', price: 30 }], isRequired: false, allowMultiple: false }] },
    ];

    const chineseMenuItems = [
      { name: 'Veg Hakka Noodles', description: 'Stir-fried noodles with mixed vegetables', category: 'Chinese', price: 160, isVeg: true, spiceLevel: 'medium', nutritionalInfo: { calories: 420, protein: 12, carbs: 65, fat: 14 }, allergens: ['Gluten', 'Soy'], portionSize: '1 serving (350g)', preparationTime: 15, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Noodle Type', options: [{ name: 'Hakka Noodles', price: 0 }, { name: 'Chow Mein', price: 0 }, { name: 'Crispy Noodles', price: 10 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (350g)', price: 0 }, { name: 'Large (500g)', price: 50 }], isRequired: false, allowMultiple: false }] },
      { name: 'Chicken Manchurian', description: 'Deep-fried chicken in spicy Manchurian sauce', category: 'Chinese', price: 240, isVeg: false, spiceLevel: 'hot', nutritionalInfo: { calories: 480, protein: 32, carbs: 38, fat: 22 }, allergens: ['Gluten', 'Soy', 'Eggs'], portionSize: '1 serving (300g)', preparationTime: 20, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Sauce Type', options: [{ name: 'Manchurian Sauce', price: 0 }, { name: 'Chili Sauce', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Add Rice/Noodles', options: [{ name: 'None', price: 0 }, { name: 'Fried Rice', price: 100 }, { name: 'Hakka Noodles', price: 100 }], isRequired: false, allowMultiple: false }] },
      { name: 'Fried Rice', description: 'Egg fried rice with vegetables', category: 'Chinese', price: 150, isVeg: false, spiceLevel: 'mild', nutritionalInfo: { calories: 420, protein: 10, carbs: 68, fat: 12 }, allergens: ['Eggs', 'Soy'], portionSize: '1 serving (300g)', preparationTime: 12, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Protein', options: [{ name: 'Egg', price: 0 }, { name: 'Chicken', price: 40 }, { name: 'Prawn', price: 60 }, { name: 'No Protein', price: -30 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (300g)', price: 0 }, { name: 'Large (500g)', price: 50 }], isRequired: false, allowMultiple: false }] },
      { name: 'Veg Manchurian', description: 'Crispy vegetable balls in spicy sauce', category: 'Chinese', price: 180, isVeg: true, spiceLevel: 'hot', nutritionalInfo: { calories: 350, protein: 8, carbs: 42, fat: 16 }, allergens: ['Gluten', 'Soy'], portionSize: '1 serving (300g)', preparationTime: 18, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Add Rice/Noodles', options: [{ name: 'None', price: 0 }, { name: 'Fried Rice', price: 100 }, { name: 'Hakka Noodles', price: 100 }], isRequired: false, allowMultiple: false }] },
      { name: 'Spring Rolls', description: 'Crispy vegetable spring rolls', category: 'Snacks', price: 120, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 240, protein: 4, carbs: 32, fat: 10 }, allergens: ['Gluten', 'Soy'], portionSize: '4 rolls', preparationTime: 10, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '4 Rolls', price: 0 }, { name: '8 Rolls', price: 120 }], isRequired: true, allowMultiple: false }, { name: 'Sauce', options: [{ name: 'Sweet & Sour Sauce', price: 0 }, { name: 'Chili Sauce', price: 0 }, { name: 'Both', price: 15 }], isRequired: false, allowMultiple: false }] },
      { name: 'Chicken Noodles', description: 'Stir-fried noodles with chicken', category: 'Chinese', price: 180, isVeg: false, spiceLevel: 'medium', nutritionalInfo: { calories: 450, protein: 20, carbs: 65, fat: 12 }, allergens: ['Gluten', 'Soy', 'Eggs'], portionSize: '1 serving (350g)', preparationTime: 15, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Noodle Type', options: [{ name: 'Hakka Noodles', price: 0 }, { name: 'Chow Mein', price: 0 }, { name: 'Crispy Noodles', price: 10 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (350g)', price: 0 }, { name: 'Large (500g)', price: 50 }], isRequired: false, allowMultiple: false }] },
      { name: 'Corn Soup', description: 'Sweet corn soup', category: 'Soups', price: 80, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 120, protein: 3, carbs: 20, fat: 3 }, allergens: ['Dairy'], portionSize: '1 bowl (250ml)', preparationTime: 8, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Size', options: [{ name: 'Regular (250ml)', price: 0 }, { name: 'Large (350ml)', price: 25 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Paneer Hakka Noodles', description: 'Hakka noodles with cottage cheese', category: 'Chinese', price: 180, isVeg: true, spiceLevel: 'medium', nutritionalInfo: { calories: 450, protein: 15, carbs: 65, fat: 14 }, allergens: ['Gluten', 'Soy', 'Dairy'], portionSize: '1 serving (350g)', preparationTime: 15, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Paneer Quantity', options: [{ name: 'Regular', price: 0 }, { name: 'Extra Paneer', price: 40 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (350g)', price: 0 }, { name: 'Large (500g)', price: 50 }], isRequired: false, allowMultiple: false }] },
      { name: 'Chow Mein', description: 'Stir-fried wheat noodles', category: 'Chinese', price: 140, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 380, protein: 8, carbs: 60, fat: 12 }, allergens: ['Gluten', 'Soy'], portionSize: '1 serving (300g)', preparationTime: 12, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (300g)', price: 0 }, { name: 'Large (450g)', price: 50 }], isRequired: false, allowMultiple: false }] },
      { name: 'Veg Fried Rice', description: 'Fried rice with mixed vegetables', category: 'Chinese', price: 130, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 380, protein: 8, carbs: 65, fat: 10 }, allergens: ['Soy'], portionSize: '1 serving (300g)', preparationTime: 12, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Portion Size', options: [{ name: 'Regular (300g)', price: 0 }, { name: 'Large (500g)', price: 50 }], isRequired: false, allowMultiple: false }] },
    ];

    const pizzaMenuItems = [
      { name: 'Margherita Pizza', description: 'Classic pizza with fresh mozzarella, tomato and basil', category: 'Pizza', price: 320, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 720, protein: 28, carbs: 85, fat: 28 }, allergens: ['Gluten', 'Dairy'], portionSize: '9 inch pizza', preparationTime: 20, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Pizza Size', options: [{ name: '9 inch', price: 0 }, { name: '12 inch', price: 100 }, { name: '14 inch', price: 150 }], isRequired: true, allowMultiple: false }, { name: 'Crust Type', options: [{ name: 'Thin Crust', price: 0 }, { name: 'Regular Crust', price: 0 }, { name: 'Stuffed Crust', price: 50 }, { name: 'Cheese Burst', price: 60 }], isRequired: true, allowMultiple: false }, { name: 'Extra Toppings', options: [{ name: 'Extra Cheese', price: 40 }, { name: 'Basil', price: 15 }, { name: 'Olives', price: 30 }], isRequired: false, allowMultiple: true }] },
      { name: 'Pepperoni Pizza', description: 'Pizza topped with spicy pepperoni and mozzarella', category: 'Pizza', price: 420, isVeg: false, spiceLevel: 'mild', nutritionalInfo: { calories: 850, protein: 35, carbs: 82, fat: 38 }, allergens: ['Gluten', 'Dairy'], portionSize: '9 inch pizza', preparationTime: 20, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Pizza Size', options: [{ name: '9 inch', price: 0 }, { name: '12 inch', price: 120 }, { name: '14 inch', price: 180 }], isRequired: true, allowMultiple: false }, { name: 'Crust Type', options: [{ name: 'Thin Crust', price: 0 }, { name: 'Regular Crust', price: 0 }, { name: 'Stuffed Crust', price: 60 }, { name: 'Cheese Burst', price: 70 }], isRequired: true, allowMultiple: false }, { name: 'Extra Toppings', options: [{ name: 'Extra Pepperoni', price: 60 }, { name: 'Extra Cheese', price: 40 }, { name: 'Bacon', price: 50 }], isRequired: false, allowMultiple: true }] },
      { name: 'Veggie Pizza', description: 'Pizza with assorted fresh vegetables', category: 'Pizza', price: 350, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 680, protein: 24, carbs: 80, fat: 26 }, allergens: ['Gluten', 'Dairy'], portionSize: '9 inch pizza', preparationTime: 20, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Pizza Size', options: [{ name: '9 inch', price: 0 }, { name: '12 inch', price: 110 }, { name: '14 inch', price: 160 }], isRequired: true, allowMultiple: false }, { name: 'Crust Type', options: [{ name: 'Thin Crust', price: 0 }, { name: 'Regular Crust', price: 0 }, { name: 'Stuffed Crust', price: 50 }, { name: 'Cheese Burst', price: 60 }], isRequired: true, allowMultiple: false }, { name: 'Vegetables', options: [{ name: 'Bell Peppers', price: 20 }, { name: 'Mushrooms', price: 25 }, { name: 'Olives', price: 30 }, { name: 'Corn', price: 20 }], isRequired: false, allowMultiple: true }] },
      { name: 'Chicken Pizza', description: 'Pizza with grilled chicken and cheese', category: 'Pizza', price: 400, isVeg: false, spiceLevel: 'mild', nutritionalInfo: { calories: 800, protein: 38, carbs: 80, fat: 35 }, allergens: ['Gluten', 'Dairy'], portionSize: '9 inch pizza', preparationTime: 22, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Pizza Size', options: [{ name: '9 inch', price: 0 }, { name: '12 inch', price: 120 }, { name: '14 inch', price: 170 }], isRequired: true, allowMultiple: false }, { name: 'Crust Type', options: [{ name: 'Thin Crust', price: 0 }, { name: 'Regular Crust', price: 0 }, { name: 'Stuffed Crust', price: 60 }, { name: 'Cheese Burst', price: 70 }], isRequired: true, allowMultiple: false }, { name: 'Chicken Style', options: [{ name: 'Grilled Chicken', price: 0 }, { name: 'Spicy Chicken', price: 20 }], isRequired: false, allowMultiple: false }, { name: 'Extra Toppings', options: [{ name: 'Extra Cheese', price: 40 }, { name: 'Bacon', price: 50 }], isRequired: false, allowMultiple: true }] },
      { name: 'Pasta Carbonara', description: 'Creamy pasta with bacon and eggs', category: 'Combos', price: 280, isVeg: false, spiceLevel: 'mild', nutritionalInfo: { calories: 620, protein: 32, carbs: 65, fat: 24 }, allergens: ['Gluten', 'Dairy', 'Eggs'], portionSize: '1 serving (350g)', preparationTime: 18, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Portion Size', options: [{ name: 'Regular (350g)', price: 0 }, { name: 'Large (500g)', price: 80 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Medium', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Extra Bacon', price: 40 }, { name: 'Extra Cheese', price: 30 }], isRequired: false, allowMultiple: true }] },
      { name: 'Garlic Bread', description: 'Toasted bread with garlic butter', category: 'Starters', price: 120, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 280, protein: 6, carbs: 35, fat: 14 }, allergens: ['Gluten', 'Dairy'], portionSize: '4 slices', preparationTime: 8, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '4 Slices', price: 0 }, { name: '8 Slices', price: 120 }], isRequired: true, allowMultiple: false }, { name: 'Topping', options: [{ name: 'Garlic Only', price: 0 }, { name: 'Garlic & Cheese', price: 30 }, { name: 'Garlic & Herbs', price: 20 }], isRequired: false, allowMultiple: false }] },
      { name: 'Caesar Salad', description: 'Crispy lettuce with parmesan and croutons', category: 'Salads', price: 200, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 320, protein: 12, carbs: 25, fat: 20 }, allergens: ['Dairy', 'Eggs'], portionSize: '1 serving (300g)', preparationTime: 8, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Protein', options: [{ name: 'No Protein', price: 0 }, { name: 'Chicken', price: 60 }, { name: 'Paneer', price: 50 }], isRequired: false, allowMultiple: false }, { name: 'Dressing', options: [{ name: 'Caesar Dressing', price: 0 }, { name: 'Light Caesar', price: 0 }, { name: 'No Dressing', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Bruschetta', description: 'Toasted bread with tomato and basil toppings', category: 'Starters', price: 140, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 180, protein: 5, carbs: 25, fat: 7 }, allergens: ['Gluten'], portionSize: '4 pieces', preparationTime: 10, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Quantity', options: [{ name: '4 Pieces', price: 0 }, { name: '6 Pieces', price: 70 }, { name: '8 Pieces', price: 140 }], isRequired: true, allowMultiple: false }, { name: 'Topping Style', options: [{ name: 'Classic Tomato', price: 0 }, { name: 'With Garlic', price: 10 }, { name: 'With Olive Oil', price: 15 }], isRequired: false, allowMultiple: false }] },
      { name: 'Tiramisu', description: 'Classic Italian layered dessert', category: 'Desserts', price: 180, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 420, protein: 8, carbs: 45, fat: 22 }, allergens: ['Dairy', 'Eggs', 'Gluten'], portionSize: '1 slice', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Serving Size', options: [{ name: '1 Slice', price: 0 }, { name: '2 Slices', price: 180 }, { name: 'Half Cake', price: 450 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Whipped Cream', price: 30 }, { name: 'Cocoa Powder', price: 0 }], isRequired: false, allowMultiple: true }] },
      { name: 'Penne Arrabbiata', description: 'Spicy tomato pasta with garlic', category: 'Combos', price: 250, isVeg: true, spiceLevel: 'hot', nutritionalInfo: { calories: 480, protein: 14, carbs: 70, fat: 14 }, allergens: ['Gluten'], portionSize: '1 serving (350g)', preparationTime: 16, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Portion Size', options: [{ name: 'Regular (350g)', price: 0 }, { name: 'Large (500g)', price: 70 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Medium', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Parmesan Cheese', price: 30 }, { name: 'Extra Garlic', price: 10 }], isRequired: false, allowMultiple: true }] },
    ];

    const fastFoodMenuItems = [
      { name: 'Veggie Burger', description: 'Vegetable patty with mayo and fresh lettuce', category: 'Burger', price: 100, isVeg: true, spiceLevel: 'mild', nutritionalInfo: { calories: 280, protein: 8, carbs: 45, fat: 10 }, allergens: ['Gluten', 'Dairy'], portionSize: '1 burger', preparationTime: 8, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Burger Size', options: [{ name: 'Single Patty', price: 0 }, { name: 'Double Patty', price: 50 }], isRequired: true, allowMultiple: false }, { name: 'Sauces', options: [{ name: 'Mayo', price: 0 }, { name: 'Mustard', price: 0 }, { name: 'Ketchup', price: 0 }, { name: 'Spicy Sauce', price: 10 }, { name: 'No Sauce', price: 0 }], isRequired: false, allowMultiple: true }, { name: 'Toppings', options: [{ name: 'Lettuce', price: 0 }, { name: 'Tomato', price: 0 }, { name: 'Onion', price: 0 }, { name: 'Cheese', price: 15 }], isRequired: false, allowMultiple: true }] },
      { name: 'Chicken Burger', description: 'Grilled chicken with cheese and mayo', category: 'Burger', price: 120, isVeg: false, spiceLevel: 'mild', nutritionalInfo: { calories: 320, protein: 18, carbs: 40, fat: 14 }, allergens: ['Gluten', 'Dairy', 'Eggs'], portionSize: '1 burger', preparationTime: 10, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Burger Size', options: [{ name: 'Single Patty', price: 0 }, { name: 'Double Patty', price: 60 }], isRequired: true, allowMultiple: false }, { name: 'Chicken Style', options: [{ name: 'Grilled', price: 0 }, { name: 'Crispy', price: 10 }], isRequired: true, allowMultiple: false }, { name: 'Sauces', options: [{ name: 'Mayo', price: 0 }, { name: 'Spicy Mayo', price: 0 }, { name: 'Garlic Sauce', price: 10 }], isRequired: false, allowMultiple: true }, { name: 'Cheese Options', options: [{ name: 'Regular Cheese', price: 0 }, { name: 'Extra Cheese', price: 20 }, { name: 'No Cheese', price: -15 }], isRequired: false, allowMultiple: false }] },
      { name: 'Spicy Paneer Burger', description: 'Fried paneer with spicy sauce and cheese', category: 'Burger', price: 110, isVeg: true, spiceLevel: 'hot', nutritionalInfo: { calories: 300, protein: 12, carbs: 42, fat: 12 }, allergens: ['Gluten', 'Dairy'], portionSize: '1 burger', preparationTime: 10, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Burger Size', options: [{ name: 'Single Patty', price: 0 }, { name: 'Double Patty', price: 55 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild', price: 0 }, { name: 'Hot', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Paneer Style', options: [{ name: 'Fried', price: 0 }, { name: 'Marinated', price: 10 }], isRequired: false, allowMultiple: false }, { name: 'Toppings', options: [{ name: 'Extra Cheese', price: 15 }, { name: 'Lettuce & Tomato', price: 0 }], isRequired: false, allowMultiple: true }] },
      { name: 'French Fries', description: 'Crispy golden fried potatoes', category: 'Snacks', price: 60, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 320, protein: 3, carbs: 40, fat: 16 }, allergens: ['None'], portionSize: '1 serving (150g)', preparationTime: 5, isAvailable: true, isBestSeller: true, customizations: [{ name: 'Size', options: [{ name: 'Small (100g)', price: 0 }, { name: 'Medium (150g)', price: 0 }, { name: 'Large (200g)', price: 30 }, { name: 'Extra Large (250g)', price: 50 }], isRequired: true, allowMultiple: false }, { name: 'Seasoning', options: [{ name: 'Plain', price: 0 }, { name: 'Salted', price: 0 }, { name: 'Chili', price: 10 }, { name: 'Cheese', price: 15 }], isRequired: false, allowMultiple: false }, { name: 'Sauce', options: [{ name: 'No Sauce', price: 0 }, { name: 'Ketchup', price: 0 }, { name: 'Mayonnaise', price: 10 }], isRequired: false, allowMultiple: true }] },
      { name: 'Cheese Fries', description: 'Fries topped with melted cheese', category: 'Snacks', price: 90, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 380, protein: 6, carbs: 42, fat: 20 }, allergens: ['Dairy'], portionSize: '1 serving (150g)', preparationTime: 7, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Size', options: [{ name: 'Regular (150g)', price: 0 }, { name: 'Large (200g)', price: 30 }, { name: 'Extra Large (250g)', price: 50 }], isRequired: true, allowMultiple: false }, { name: 'Cheese Type', options: [{ name: 'Regular Cheese', price: 0 }, { name: 'Extra Cheese', price: 20 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Bacon Bits', price: 30 }, { name: 'Jalapeños', price: 10 }], isRequired: false, allowMultiple: true }] },
      { name: 'Spicy Fries', description: 'Fries with spicy chili seasoning', category: 'Snacks', price: 70, isVeg: true, spiceLevel: 'hot', nutritionalInfo: { calories: 340, protein: 3, carbs: 42, fat: 17 }, allergens: ['None'], portionSize: '1 serving (150g)', preparationTime: 6, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Size', options: [{ name: 'Small (100g)', price: 0 }, { name: 'Medium (150g)', price: 0 }, { name: 'Large (200g)', price: 25 }], isRequired: true, allowMultiple: false }, { name: 'Spice Level', options: [{ name: 'Mild Spice', price: 0 }, { name: 'Hot Spice', price: 0 }, { name: 'Extra Hot', price: 0 }], isRequired: false, allowMultiple: false }, { name: 'Sauce', options: [{ name: 'No Sauce', price: 0 }, { name: 'Ranch Sauce', price: 10 }, { name: 'Garlic Sauce', price: 10 }], isRequired: false, allowMultiple: true }] },
      { name: 'Cold Drink', description: 'Chilled soft drink', category: 'Beverages', price: 30, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 140, protein: 0, carbs: 39, fat: 0 }, allergens: ['None'], portionSize: '250ml', preparationTime: 1, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Drink Type', options: [{ name: 'Cola', price: 0 }, { name: 'Lemon', price: 0 }, { name: 'Orange', price: 0 }, { name: 'Sprite', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Size', options: [{ name: 'Small (250ml)', price: 0 }, { name: 'Medium (350ml)', price: 10 }, { name: 'Large (500ml)', price: 20 }], isRequired: true, allowMultiple: false }, { name: 'Temperature', options: [{ name: 'Cold', price: 0 }, { name: 'Ice Cold', price: 0 }], isRequired: false, allowMultiple: false }] },
      { name: 'Milkshake', description: 'Thick creamy milkshake', category: 'Beverages', price: 80, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 280, protein: 5, carbs: 45, fat: 8 }, allergens: ['Dairy'], portionSize: '1 glass (300ml)', preparationTime: 5, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Flavor', options: [{ name: 'Vanilla', price: 0 }, { name: 'Chocolate', price: 0 }, { name: 'Strawberry', price: 0 }, { name: 'Mango', price: 0 }], isRequired: true, allowMultiple: false }, { name: 'Size', options: [{ name: 'Regular (300ml)', price: 0 }, { name: 'Large (500ml)', price: 40 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Whipped Cream', price: 20 }, { name: 'Extra Syrup', price: 15 }, { name: 'Nuts', price: 20 }], isRequired: false, allowMultiple: true }] },
      { name: 'Cheesecake', description: 'Delicious creamy cheesecake', category: 'Desserts', price: 80, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 350, protein: 6, carbs: 42, fat: 18 }, allergens: ['Dairy', 'Gluten', 'Eggs'], portionSize: '1 slice', preparationTime: 2, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Serving Size', options: [{ name: '1 Slice', price: 0 }, { name: '2 Slices', price: 80 }, { name: 'Half Cake', price: 320 }], isRequired: true, allowMultiple: false }, { name: 'Topping', options: [{ name: 'Plain', price: 0 }, { name: 'Chocolate Sauce', price: 20 }, { name: 'Fruit Topping', price: 30 }, { name: 'Both', price: 45 }], isRequired: false, allowMultiple: false }]} ,
      { name: 'Brownie', description: 'Rich chocolate brownie', category: 'Desserts', price: 70, isVeg: true, spiceLevel: 'not-applicable', nutritionalInfo: { calories: 400, protein: 5, carbs: 50, fat: 20 }, allergens: ['Dairy', 'Gluten', 'Eggs'], portionSize: '1 piece', preparationTime: 2, isAvailable: true, isBestSeller: false, customizations: [{ name: 'Serving Size', options: [{ name: '1 Piece', price: 0 }, { name: '2 Pieces', price: 70 }, { name: 'Whole Brownie', price: 280 }], isRequired: true, allowMultiple: false }, { name: 'Add-ons', options: [{ name: 'Vanilla Ice Cream', price: 40 }, { name: 'Chocolate Ice Cream', price: 40 }, { name: 'Whipped Cream', price: 25 }], isRequired: false, allowMultiple: true }] }
    ];

    for (let i = 0; i < restaurants.length; i++) {
      let menuItems = [];

      if (i % 5 === 0) menuItems = biryaniMenuItems;
      else if (i % 5 === 1) menuItems = southIndianMenuItems;
      else if (i % 5 === 2) menuItems = chineseMenuItems;
      else if (i % 5 === 3) menuItems = pizzaMenuItems;
      else if (i % 5 === 4) menuItems = fastFoodMenuItems;

      await MenuItem.create(createMenuItems(restaurants[i]._id, menuItems));
    }

    for (let i = 0; i < owners.length; i++) {
      owners[i].restaurant = restaurants[i]._id;
      await owners[i].save();
    }

    console.log('Creating sample customers...');
    await User.create([
      {
        name: 'Test Customer 1',
        email: 'customer1@seed.com',
        password: 'password123',
        phone: '9876543300',
        role: 'customer',
        authProvider: 'local',
        addresses: [
          {
            label: 'home',
            street: 'HSR Layout',
            city: 'Bangalore',
            state: 'Karnataka',
            pincode: '560102',
            landmark: 'Near Agara Lake',
            isDefault: true
          }
        ]
      },
      {
        name: 'Test Customer 2',
        email: 'customer2@seed.com',
        password: 'password123',
        phone: '9876543301',
        role: 'customer',
        authProvider: 'local',
        addresses: [
          {
            label: 'home',
            street: 'Bandra',
            city: 'Mumbai',
            state: 'Maharashtra',
            pincode: '400050',
            landmark: 'Linking Road',
            isDefault: true
          }
        ]
      }
    ]);

    console.log('Seed data created successfully!');
    console.log('\nSummary:');
    console.log(`   ✓ 30 restaurant owners created`);
    console.log(`   ✓ 30 restaurants created (5 per city)`);
    console.log(`   ✓ 300+ menu items created (10 per restaurant)`);
    console.log(`   ✓ 2 sample customers created`);
    console.log('\nCities:');
    console.log(`   • Anantapur • Bangalore • Mumbai • Delhi • Hyderabad • Pune`);
    console.log('\nLogin Credentials:');
    console.log(`   Restaurant Owner: raj1@seed.com / password123`);
    console.log(`   Customer: customer1@seed.com / password123`);
    console.log('\nAll data validated against model schemas!');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error.message);
    process.exit(1);
  }
};

seedData();